version: '3.9'

services:
  traefik:
    image: traefik:v2.11
    restart: always
    container_name: traefik
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.elasticsearch.address=:9200"
      - "--entrypoints.kibana.address=:5601"
    ports:
      - "9200:9200"
      - "5601:5601"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - elasticsearch_cluster

  es01:
    image: elasticsearch:8.12.2
    restart: always
    container_name: es01
    environment:
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elasticsearch.rule=Host(`localhost`)"
      - "traefik.http.routers.elasticsearch.entrypoints=elasticsearch"
      - "traefik.http.services.elasticsearch.loadbalancer.server.port=9200"
    volumes:
        - es01_data:/usr/share/elasticsearch/data
    networks:
        - elasticsearch_cluster

  es02:
    image: elasticsearch:8.12.2
    restart: always
    container_name: es02
    environment:
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elasticsearch.rule=Host(`localhost`)"
      - "traefik.http.routers.elasticsearch.entrypoints=elasticsearch"
      - "traefik.http.services.elasticsearch.loadbalancer.server.port=9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - es01
    volumes:
        - es02_data:/usr/share/elasticsearch/data
    networks:
        - elasticsearch_cluster

  es03:
    image: elasticsearch:8.12.2
    restart: always
    container_name: es03
    environment:
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elasticsearch.rule=Host(`localhost`)"
      - "traefik.http.routers.elasticsearch.entrypoints=elasticsearch"
      - "traefik.http.services.elasticsearch.loadbalancer.server.port=9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - es02
    volumes:
        - es03_data:/usr/share/elasticsearch/data
    networks:
        - elasticsearch_cluster

  kibana:
    image: kibana:8.12.2
    restart: always
    container_name: kibana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kibana.rule=Host(`localhost`)"
      - "traefik.http.routers.kibana.entrypoints=kibana"
      - "traefik.http.services.kibana.loadbalancer.server.port=5601"
    networks:
      - elasticsearch_cluster

volumes:
  es01_data:
  es02_data:
  es03_data:

networks:
  elasticsearch_cluster:
    driver: bridge